#!/bin/bash

# Copyright (C) 2025 Dyne.org Foundation
#
# Designed, written and maintained by Denis Roio <jaromil@dyne.org>
#
# This source code is free software; you can redistribute it and/or
# modify it under the terms of the GNU Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This source code is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	Please refer
# to the GNU Public License for more details.
#
# You should have received a copy of the GNU Public License along with
# this source code; if not, , see <https://www.gnu.org/licenses/>.

TMP="$BATS_TEST_TMPDIR"
T="$BATS_TEST_DIRNAME"
export FILES_DIR="$T"
export SRC="${T}"
mkdir -p "$SRC"
load bats/test_helper/bats_support/load
load bats/test_helper/bats_assert/load
load bats/test_helper/bats_file/load
function _out() {     printf "$*\n"; }
function _err() { >&2 printf "$*\n" | tee -a $TMP/err; }

luaexec() {
  set +e
  local lua
  local data
  local keys
  [ "$1" == "" ] || lua="$1"
  [ "$2" == "" ] || data="-a ${SRC}/$2"
  [ "$3" == "" ] || keys="-k ${SRC}/$3"
  [ -r "${lua}" ] || {
    _err "Error: script not found: $lua"
    exit 1;  }
  # EXECUTION (timed)
  >&3 echo " 🔥 `basename ${lua}`"
  [ "$data" == "" ] || >&3 echo " 📄 `basename $data`"
  [ "$keys" == "" ] || >&3 echo " 🔑 `basename $keys`"

  local start_time_s=$(date +%s)
  local start_time_ns=$(date +%N)
  zenroom \
    $lua $data $keys \
    1>$TMP/out 2> >(tee $TMP/err | grep -v 'J64 ' >&2)
  local res=$?
  local end_time_s=$(date +%s)
  local end_time_ns=$(date +%N)
  export output=`cat $TMP/out`
  [ "$output" == "" ] && {
    _err "Output is missing, no result from previous computation"
    exit 1;  }
  # Calculate execution timing:
  # avoid leading zero issues in shell by normalizing inputs
  start_time_s=$((10#$start_time_s))
  start_time_ns=$((10#$start_time_ns))
  end_time_s=$((10#$end_time_s))
  end_time_ns=$((10#$end_time_ns))
  # Convert and calculate elapsed time in milliseconds
  local start_time_ms=$((start_time_s * 1000 + start_time_ns / 1000000))
  local end_time_ms=$((end_time_s * 1000 + end_time_ns / 1000000))
  local execution_time_ms=$((end_time_ms - start_time_ms))
  # Write the output
    mv "$TMP/out" "${lua}.out.json"
  >&3 echo "  💾 `basename ${lua}.out.json`"
  # >&3 echo "$output"
  set -e # relax
}
